### ISSUE TITLE
I try to using cryptoalarm on CentOS 7 but found some error.

### ISSUE THREAD

**Issue by chanwitkepha** [nesfit/jane-cryptoalarm#6]
I test it on CentOS 7, Install local-persist driver, use `docker-compose pull ` according to README.md. But when I start service with `docker-compose up -d `command. It have error like this. Please help, Thank you.

![error-01](https://user-images.githubusercontent.com/45688421/173793624-0554e861-a784-4d07-b0c4-6f34eef59488.jpg)

**Comment by SpiderBraids** [comment]
According to the file "cryptoalarm-web/laravel/config/app.php" the `key` value in the config is derived from the `APP_KEY` environment variable. An application key can be generated using the command `php artisan key:generate` within the `cryptoalarm-web` container and inserted into `/cryptoalarm-web/config/.env`.

**Comment by chanwitkepha** [comment]
> According to the file "cryptoalarm-web/laravel/config/app.php" the `key` value in the config is derived from the `APP_KEY` environment variable. An application key can be generated using the command `php artisan key:generate` within the `cryptoalarm-web` container and inserted into `/cryptoalarm-web/config/.env`.

Thank you for your help.
